# Generated by Django 2.2.4 on 2019-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191217_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='imdbID',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
