# Generated by Django 2.2.4 on 2019-12-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191217_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['title']},
        ),
    ]
