# Generated by Django 2.1.5 on 2019-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_providers_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='on_plex',
            field=models.BooleanField(default=False),
        ),
    ]
