# Generated by Django 4.1.4 on 2022-12-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_media_on_plex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Torrents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnet', models.URLField()),
                ('status', models.CharField(choices=[('COMPLETE', 'complete'), ('IN-PROGRESS', 'in-progress'), ('READY', 'ready')], max_length=11)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.media')),
            ],
        ),
    ]
